# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

notifications:
  email: false

sudo: required

addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgtk-3-0

## Allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

before_script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then GUITESTCMD="xvfb-run julia"; else GUITESTCMD="julia"; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok; sleep 3 )& fi
  - julia -e 'VERSION >= v"0.7-" && using Pkg; Pkg.clone(pwd()); Pkg.build("Libui");'

##uncomment the following lines to override the default test script
script:
  - ${GUITESTCMD} -e 'VERSION >= v"0.7-" && using Pkg; Pkg.test("Libui"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'VERSION >= v"0.7-" && using Pkg; cd(Pkg.dir("Libui")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'VERSION >= v"0.7-" && using Pkg; cd(Pkg.dir("Libui")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
